# SQLite
spring.datasource.url=jdbc:sqlite:./smartquery.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Lucene
lucene.index.path=./lucene-index

# JWT
jwt.access-token-expiry-ms=900000
jwt.refresh-token-expiry-ms=604800000
jwt.keys-dir=./keys

# Server
server.port=8080
server.tomcat.max-http-header-size=131072
spring.application.name=smartquery-server
